// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8DAFrCthtT53-O51DosqEt7X8AZV-UHI',
    appId: '1:771237132618:web:3351249cdccada159e29b3',
    messagingSenderId: '771237132618',
    projectId: 'perpustakaan-12',
    authDomain: 'perpustakaan-12.firebaseapp.com',
    storageBucket: 'perpustakaan-12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD187TJLUIwsST2jXZqbpmEzhj6ut2_1cQ',
    appId: '1:771237132618:android:28936d0f196e21ae9e29b3',
    messagingSenderId: '771237132618',
    projectId: 'perpustakaan-12',
    storageBucket: 'perpustakaan-12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuQc1MQVWuo5jDt-zFHGFmazYkRQxulKY',
    appId: '1:771237132618:ios:d3c034f674ac0c929e29b3',
    messagingSenderId: '771237132618',
    projectId: 'perpustakaan-12',
    storageBucket: 'perpustakaan-12.firebasestorage.app',
    iosBundleId: 'com.example.perpustakaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuQc1MQVWuo5jDt-zFHGFmazYkRQxulKY',
    appId: '1:771237132618:ios:d3c034f674ac0c929e29b3',
    messagingSenderId: '771237132618',
    projectId: 'perpustakaan-12',
    storageBucket: 'perpustakaan-12.firebasestorage.app',
    iosBundleId: 'com.example.perpustakaan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8DAFrCthtT53-O51DosqEt7X8AZV-UHI',
    appId: '1:771237132618:web:7dcb137afea0d7fc9e29b3',
    messagingSenderId: '771237132618',
    projectId: 'perpustakaan-12',
    authDomain: 'perpustakaan-12.firebaseapp.com',
    storageBucket: 'perpustakaan-12.firebasestorage.app',
  );
}
